-- 012: ingest 可靠性 — 从 spec §6.1 提取
ALTER TABLE ingest_jobs ALTER COLUMN status TYPE VARCHAR(40);
ALTER TABLE ingest_jobs ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ingest_jobs ADD COLUMN IF NOT EXISTS max_retries INTEGER NOT NULL DEFAULT 3;
ALTER TABLE ingest_jobs ADD COLUMN IF NOT EXISTS cancel_requested BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ingest_jobs ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMPTZ;
ALTER TABLE ingest_jobs ADD COLUMN IF NOT EXISTS item_states JSONB NOT NULL DEFAULT '[]'::jsonb;
